import axios from 'axios';
import fs from 'fs';

const API = process.env.API_BASE || process.env.APP_BASE_URL?.replace(/\/$/, '')?.replace(/https?:\/\//, '') ? `http://${process.env.API_BASE || 'localhost:5000'}/api` : (process.env.API_URL || 'http://localhost:5000/api');
// simplify: default to http://localhost:5000/api
const BASE = process.env.API_BASE_URL || 'http://localhost:5000/api';

async function run() {
  try {
    const email = `test+${Date.now()}@example.org`;
    const password = 'Password123!';

    console.log('Registering user', email);
    let token, user;
    try {
      const reg = await axios.post(`${BASE}/auth/register`, { name: 'E2E Test', email, password });
      token = reg.data.data.token;
      user = reg.data.data.user;
    } catch (e) {
      console.warn('Register failed, attempting login', e.message);
      const lg = await axios.post(`${BASE}/auth/login`, { email, password });
      token = lg.data.data.token;
      user = lg.data.data.user;
    }

    axios.defaults.headers.common['Authorization'] = `Bearer ${token}`;

    console.log('Generating FIR draft');
    const incident = {
      title: 'E2E Test FIR',
      incidentDetails: 'Test incident details generated by e2e script.',
      incidentDate: new Date().toISOString(),
      incidentLocation: 'Test Location',
      complainantDetails: { name: 'Test User', email },
    };

    const gen = await axios.post(`${BASE}/fir/generate/${user._id}`, { incidentData: incident, language: 'en' });
    const fir = gen.data.data;
    console.log('Generated FIR id', fir._id || fir.id);

    console.log('Finalizing FIR');
    await axios.post(`${BASE}/fir/finalize/${fir._id || fir.id}`);

    console.log('Downloading PDF');
    const pdfRes = await axios.get(`${BASE}/fir/pdf/${fir._id || fir.id}`, { responseType: 'arraybuffer' });
    const outPath = `./test-output/FIR-${fir._id || fir.id}.pdf`;
    fs.mkdirSync('./test-output', { recursive: true });
    fs.writeFileSync(outPath, pdfRes.data);

    console.log('Saved PDF to', outPath);
  } catch (err) {
    console.error('E2E run failed', err.response?.data || err.message || err);
    process.exit(1);
  }
}

run();
